DELETE  http://localhost:3003/api/blogs/6408c53dbb15316a8b12f4a6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImloYW11bWEiLCJpZCI6IjY0MDhiNGJmZTMzZDQ0ODAxOTYwYmNiZCIsImlhdCI6MTY3ODYzMjE0NSwiZXhwIjoxNjc4NjM1NzQ1fQ.pEAPM70G0y0Mac_CFlj08qtl-u3YwK7pUMzQnv0SdDA